version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    ports:
      - "9201:9201"
      - "9301:9301"
    environment:
      - discovery.type=single-node
  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "18087:18087"
